name: 🐛 Bug Report
description: Report a bug or issue with the React Developer Assignment
title: "🐛 [Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        
        Thank you for taking the time to report a bug! Please fill out this form to help us understand and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: 📋 Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tested this on the latest version
          required: true
        - label: I have provided detailed reproduction steps
          required: true

  - type: dropdown
    id: component
    attributes:
      label: 🎯 Component/Feature
      description: Which part of the application is affected?
      options:
        - Property Listing Dashboard
        - Portfolio Generator
        - Template Selection
        - Portfolio Builder
        - Portfolio Preview
        - Navigation/Routing
        - Dark Mode Toggle
        - Responsive Design
        - Search/Filtering
        - Forms/Modals
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 📊 Bug Severity
      description: How severe is this bug?
      options:
        - 🔴 Critical - App crashes or major functionality broken
        - 🟠 High - Important feature not working
        - 🟡 Medium - Minor feature issue or visual bug
        - 🟢 Low - Cosmetic issue or minor inconvenience
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened instead?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: 🌐 Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: 📱 Browser Version
      description: What version of the browser?
      placeholder: e.g., Chrome 120.0.6099.109
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: 📱 Device Type
      description: What type of device are you using?
      options:
        - Desktop
        - Laptop
        - Tablet
        - Mobile Phone
        - Other

  - type: dropdown
    id: os
    attributes:
      label: 💻 Operating System
      description: What operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS
        - Linux
        - iOS
        - Android
        - Other

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots/Videos
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here or paste image URLs...

  - type: textarea
    id: console-errors
    attributes:
      label: 🔧 Console Errors
      description: Any error messages from the browser console?
      placeholder: |
        Open browser DevTools (F12) → Console tab → Copy any error messages here
      render: javascript

  - type: textarea
    id: additional-context
    attributes:
      label: 💡 Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help us understand the issue...

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: Would you like to contribute to fixing this bug?
      options:
        - label: I would like to work on fixing this bug
        - label: I can provide additional testing
        - label: I can help with documentation updates 